### ISSUE TITLE
login error

### ISSUE THREAD

**Issue by typchik** [undmrz/plexplugins#1]
FreeBSD 9.2-RELEASE-p4
plex 0.9.9.13
![2014-08-20 0 46 13](https://cloud.githubusercontent.com/assets/8217798/3972887/e1f59ad0-27e1-11e4-826b-60565da23094.png)

**Comment by iChicory** [comment]
Same for FreeBSD 9.x and plex 0.9.9.14

**Comment by sasbizt** [comment]
+1
Mac OS 10.10, PMS 0.9.9.16.555-50CD0C3

**Comment by samosad** [comment]
+1
Maverics, PMS 0.9.9.14

**Comment by vs40** [comment]
Same with OSX 10.9.5 + PMS 0.9.9.14.531-7eef8c6

**Comment by fuksman** [comment]
+1
Mac OS 10.10, PMS 0.9.9.14.531-7eef8c6

**Comment by vs40** [comment]
Also Im tried it on windows.
I can see TOP menu and few menus in GENDER, but must part of menus still require the password.

**Comment by webserfer** [comment]
Same for nas4free.

**Comment by vs40** [comment]
Still no news about update? (

**Comment by Dewsmen** [comment]
Check my fixes in [fork](https://github.com/Dewsmen/plexplugins)

**Comment by samosad** [comment]
Thank you man!!

**Comment by vs40** [comment]
Thank you Dewsmen! 
Now its working!
